name: Create or Update WCAG Violation Issues

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-or-update-issues:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issues-markdown directory
        run: |
          mkdir -p issues-markdown
          echo "Created issues-markdown directory"

      - name: Create or Update GitHub Issues for Violations
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            console.log("Starting WCAG violation issue creation workflow...");

            function getLatestReportFolder(baseDir) {
              console.log(`Checking for the latest report folder in: ${baseDir}`);
              if (!fs.existsSync(baseDir)) {
                console.warn(`Directory ${baseDir} does not exist.`);
                return null;
              }

              const subdirs = fs.readdirSync(baseDir)
                .filter(name => {
                  const fullPath = path.join(baseDir, name);
                  return fs.statSync(fullPath).isDirectory() && 
                         name !== 'summaries' && 
                         /^\d{4}-\d{2}-\d{2}$/.test(name);
                })
                .sort((a, b) => b.localeCompare(a));

              if (subdirs.length === 0) {
                console.log("No dated subdirectories found in accessibility-reports.");
                return null;
              }

              const latestFolder = subdirs[0];
              console.log(`Latest report folder selected: ${latestFolder}`);
              return path.join(baseDir, latestFolder);
            }

            function getLatestSummaryFile(summariesDir) {
              console.log(`Checking for the latest daily summary in: ${summariesDir}`);
              if (!fs.existsSync(summariesDir)) {
                console.warn(`Directory ${summariesDir} does not exist.`);
                return null;
              }

              const subdirs = fs.readdirSync(summariesDir)
                .filter(name => fs.statSync(path.join(summariesDir, name)).isDirectory())
                .sort((a, b) => b.localeCompare(a));

              if (subdirs.length === 0) {
                console.log("No subdirectories found in summaries.");
                return null;
              }

              const latestSummaryFolder = subdirs[0];
              const summaryFile = path.join(summariesDir, latestSummaryFolder, 'daily_summary.json');
              if (fs.existsSync(summaryFile)) {
                console.log(`Latest daily summary file found: ${summaryFile}`);
                return summaryFile;
              }

              console.log("No daily_summary.json found in latest folder.");
              return null;
            }

            // (All your existing JS logic unchanged — omitted for brevity)

            console.log("WCAG violation issue creation workflow completed.");

      - name: Commit and Push Markdown Files to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -d "issues-markdown" ] && [ -n "$(ls -A issues-markdown 2>/dev/null)" ]; then
            echo "Found markdown files to commit"
            git add issues-markdown/
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update WCAG violation markdown reports [skip ci]"
              git push origin gh-pages
              echo "Markdown files committed and pushed to gh-pages"
            fi
          else
            echo "No markdown files to commit"
          fi