name: WCAG Accessibility Testing (Azure runner)
on:
  #schedule:
    #- cron: '0 0 * * *'  # Fixed cron syntax
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  trigger-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: azureuser  # Changed to azureuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            echo "Active user: $(whoami)"
            echo "Home directory: $HOME"
            echo "Checking actions-runner directory:"
            ls -la /home/azureuser/actions-runner || echo "Directory not found"  # Updated path to azureuser
            cd /home/azureuser/actions-runner || echo "Failed to navigate"  # Updated path to azureuser
            pwd
            ls -la
            echo "Testing run.sh execution:"
            ./run.sh || echo "run.sh execution failed"

      - name: Execute Script in Correct Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: azureuser  # Changed to azureuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd /home/azureuser/actions-runner  # Updated path to azureuser
            echo "Running run.sh script:"
            bash run.sh

  test-and-deploy:
    runs-on: self-hosted
    needs: trigger-runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Install Playwright
        run: |
          npx playwright install chromium firefox webkit --with-deps
      
      - name: Run WCAG Tests
        run: |
          for spec in tests/*.spec.ts; do
            npx playwright test "$spec" --workers=1 || echo "Test completed with violations"
          done
        continue-on-error: true
        
      - name: Prepare GitHub Pages
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          mkdir -p gh-pages-branch/accessibility-reports gh-pages-branch/historical-data
          
          # Copy reports and artifacts
          cp -r accessibility-reports/* gh-pages-branch/accessibility-reports/ || true
          cp -r playwright-report/* "gh-pages-branch/historical-data/${TIMESTAMP}-report/" || true
          cp {all,index,bar}.html gh-pages-branch/
          cp favicon.ico gh-pages-branch/
          
          # Generate report list
          find gh-pages-branch/accessibility-reports -name "violations-*.json" -type f | \
            jq -R . | jq -s . > gh-pages-branch/historical-data/report-list.json
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-branch
          publish_branch: gh-pages
          keep_files: true
