name: WCAG Accessibility Testing (Test & Deploy)
on:
  workflow_run:
    workflows: ["Trigger Runner Setup"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Install Playwright Dependencies
        run: npx playwright install chromium --with-deps
      
      - name: Run WCAG Tests
        run: npx playwright test || echo "Test completed with violations"
        continue-on-error: true
      
      - name: Prepare GitHub Pages
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          mkdir -p gh-pages-branch/accessibility-reports gh-pages-branch/historical-data
          
          cp -r accessibility-reports/* gh-pages-branch/accessibility-reports/ || true
          cp -r playwright-report/* "gh-pages-branch/historical-data/${TIMESTAMP}-report/" || true
          cp {all,index,bar}.html gh-pages-branch/
          cp favicon.ico gh-pages-branch/
          
          find gh-pages-branch/accessibility-reports -name "violations-*.json" -type f | \
            jq -R . | jq -s . > gh-pages-branch/historical-data/report-list.json
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-branch
          publish_branch: gh-pages
          keep_files: true